version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_container
    ports:
      - "5430:5432"
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
